name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Test Docker Build
        run: docker build -t devops-population-app .